version: '3'
services:
  preact-boilerplate:
    working_dir: /app
    build: .
    user: pptruser
    command: npm run dev:watch
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    ports:
      - 3030:3030
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
